---
version: "3"

volumes:
  clickhouse-data:

services:
  clickhouse:
    image: clickhouse/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - IPC_LOCK
    volumes:
      - clickhouse-data:/var/lib/clickhouse
  qryn:
    image: qxip/qryn:v2.1.42
    ports:
      - "3100:3100"
    environment:
      - CLICKHOUSE_SERVER=clickhouse
      - "CLICKHOUSE_AUTH=default:"
      - CLICKHOUSE_PROTO=http
      - CLICKHOUSE_PORT=8123
      - CLICKHOUSE_DB=qryn
  grafana:
    image: grafana/grafana:9.2.4
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    depends_on:
      - qryn
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
          - name: Qryn
            type: loki
            access: proxy
            url: http://qryn:3100
        EOF
        /run.sh
    ports:
      - "3000:3000"
  flog:
    image: mingrammer/flog
    command: -f json -d 1s -l
  promtail:
    image: grafana/promtail:2.6.1
    volumes:
      - ./promtail-local-config.yaml:/etc/promtail/config.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/config.yaml
    depends_on:
      - flog
